### ISSUE TITLE
Cannot deploy to server due to swift version and package conflicts

### ISSUE THREAD

**Issue by zirinisp** [IBM-Swift/Kitura-Starter-Bluemix#11]
I am new to Kitura and Bluemix and I am currently trying them out. After a lot of troubleshooting and messing around with swift and package versions, I have managed to setup a Kitura Server that could run from Xcode.

The setup is quite basic, all I currently need from the app is to retrieve a table from an mlab database. I could not accomplish that with Swift 2016_06_06 and could only get it to work with 2016_08_23. My package.swift file is the following:

`import PackageDescription

let package = Package(
    name: "KiteSpotterBluemix",
    targets: [
        Target(
            name: "KiteSpotterBluemix",
            dependencies: []
        )
    ],
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 0, minor: 28),
        .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 0, minor: 15),
        .Package(url:"https://github.com/PerfectlySoft/Perfect-MongoDB.git", versions: Version(0,0,0)..<Version(10,0,0))

    ]
)
`

Problem with 2016_08_23 is that it cannot be deployed to BlueMix and I get the following error:

`-----> Installing Swift DEVELOPMENT-SNAPSHOT-2016-08-23-a
DEPENDENCY_MISSING_IN_MANIFEST: 'swift-DEVELOPMENT-SNAPSHOT-2016-08-23-a.tar.gz'
Staging failed: Buildpack compilation step failed
`

I have tried to play with a number of version combination to get it to work locally with 2016_06_06, but did not succeed. 

Is there any solution to that, wither by using 2016_08_23 or 2016_06_06?

**Comment by rolivieri** [comment]
I apologize for not responding sooner. We were in the middle of upgrades. We have updated the code to be now compatible with swift 3.0. Can you pull from master again and try one more time?

**Comment by zirinisp** [comment]
I can understand the pressure you are under, as I am currently doing the same for all my apps and it is a very long process.

That is great to hear as with the beta releases it was a bit of a mess. You have done a great job so far. Once I finish with the upgrades I will try it out again.

I am trying to replace Parse Server with Kitura. So far I managed to connect mongodb. The next step is user authentication. Can you guide me on which packages to use to accomplish that. Credentials are currently stored in mongo.

**Comment by shmuelk** [comment]
@zirinisp Kitura has a family of Kitura-Credentials* repositories for doing authorization. 

How you should integrate your database based credentials, I think depends mostly on how you want the clients to send the credentials to the serer for checking. If you plan on using either HTTP Digest authentication or HTTP Basic authentication, look at the Kitura-CredentialsHTTP repository. It is a plugin for our Kitura-Credentials repository for working with credentials passed via HTTP Digest or HTTP Basic authentication. You supply a function that actually checks the credentials sent over the wire. Your function could simply access your database.

**Comment by rolivieri** [comment]
Closing issue; this has been solved.
