### ISSUE TITLE
Enhance sample to include JSON response

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-Starter-Bluemix#13]
Currently, the two route use normal text responses, which is not standard for most apps.  The responses should be sent in JSON format.

**Comment by rolivieri** [comment]
Added a new endpoint that returns JSON; updated the README to document the changes. I'd like to keep the existing text/plain endpoints as well.

**Comment by kfbishop** [comment]
Sounds perfect. thanks.  I'll let you close once fully implemented.

**Comment by rolivieri** [comment]
Sounds good! Closing issue; changes are in master and develop branches.
