### ISSUE TITLE
Remove confusion for default route

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-Starter-Bluemix#14]
Currently, the app's default route returns a complex Kitura page. This is nice, but confusing when trying to learn how to use Kitura, as its very unclear to the user where this page is coming from.   The sample should show a simple file based response coming directly form thr sample project itself, not from embedded Kitura.

**Comment by rolivieri** [comment]
Great point; changes made, tested, and pushed. Closing issue.
