### ISSUE TITLE
Add "buildpack: url" line to manifest.yml

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-Starter-Bluemix#15]
By defaulting this line in the manifest.yml file, it would remove confusion when non-default toolchain is requested.

TBD: Is there *any* deployment time penalty for using external buildpack vs default one provided by BMX?

**Comment by rolivieri** [comment]
With the latest changes, the manifest now contains the buildpack attribute. However, it does not point to a URL. Instead, it uses the buildpack name. Yes, there is a performance penalty if using the url instead of the installed version of the buildpack.

**Comment by kfbishop** [comment]
OK, thanks for the details.
