### ISSUE TITLE
Fails to generate Xcodeproj with Swift Package Manager

### ISSUE THREAD

**Issue by egross91** [IBM-Swift/Kitura-Starter-Bluemix#16]
When generating a `.xcodeproj` file, it fails during SwiftJSON because of the error

> error: The package at `/Users/ericgross/Documents/Projs/git kitura 2/Packages/SwiftyJSON.git' has no Package.swift for the specific version: 9.0.0

**Comment by kweinmeister** [comment]
The master branch is using the `06-06` version of Swift and an old version of Kitura. Can you check if the issue still can be reproduced on the develop branch?

**Comment by egross91** [comment]
Successful on develop branch.

**Comment by kweinmeister** [comment]
Thanks for confirming.

**Comment by rolivieri** [comment]
Master branch has been updated and it now contains code that is compatible with swift 3.0. Closing this issue.
