### ISSUE TITLE
Ensure compliance with Bluemix Samples standards

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-Starter-Bluemix#17]
Re: https://github.com/IBM-Bluemix/repo-guidelines

We need to review current README and content to make sure we are following the spirit of Bluemix samples, such that we have a consistent experience.

Note: it is expected that the specific guidance for runtime samples will be evolving in the near future, so we need to keep on eye on this moving forward.

**Comment by rolivieri** [comment]
Issue is being tracked here: https://github.ibm.com/Bluemix/developer-productivity/issues/172

**Comment by rolivieri** [comment]
Compliance has been met. Closing this issue. We will use #18 to track the progress of migrating this repo to its new home.
