### ISSUE TITLE
To deploy/run the app on cloud, instructions must clearly indicate the use of IP address 

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Swift/Kitura-Starter-Bluemix#21]
I am not sure if this is the correct repository for this issue.

The [instructions](http://www.kitura.io/en/starter/deploying.html) to deploy the app to cloud and run using Docker should clearly indicate that the browser on the host machine should use the IP address to run the app.

Perhaps, a new Step 6 can be added to the existing list of steps as shown below:

```
6. Point your browser(running on the host machine) to point at
http://<ip-address-from-DOCKER_HOST-env-variable>:8090/hello
```

**Comment by ianpartridge** [comment]
Fixed in the Kitura issue.
