### ISSUE TITLE
Deploy to Bluemix button not working

### ISSUE THREAD

**Issue by kfbishop** [IBM-Swift/Kitura-Starter-Bluemix#5]
Testing Kitura-Starter, and using the “Deploy to Bluemix” is failing when jazzhub tries to validate the GH project url.

![image](https://cloud.githubusercontent.com/assets/300008/16657320/1684e2bc-4430-11e6-94c4-f19428f183ca.png)

`{"Severity":"Error","Message":"URL does not point to a valid Git repository","HttpCode":422,"BundleId":"org.eclipse.orion.server.core","Code":0,"DetailedMessage":"https://github.com/IBM-Swift/Kitura-Starter-Bluemix/tree/master: https://github.com/IBM-Swift/Kitura-Starter-Bluemix/tree/master/info/refs?service=git-upload-pack not found"}`

**Comment by rolivieri** [comment]
@kfbishop I just tried using the deploy to bluemix button and it worked fine. Do you know the steps you took?

<img width="731" alt="screen shot 2016-07-11 at 3 14 24 pm" src="https://cloud.githubusercontent.com/assets/6609246/16745248/9e5afa1c-477a-11e6-8c96-62c88260f17e.png">

**Comment by kfbishop** [comment]
Hmm..   worked fine for me now too.   I'll chalk it up to the issues BMX was having last week.
